name: Continuous Deploy 
on:
  push:
    branches:
      - main  
    paths-ignore:   
      - README.md
      - LICENSE

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build 

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: '${{ secrets.SERVER_USERNAME }}'
          port: '${{ secrets.SERVER_PORT }}'
          server: '${{ secrets.SERVER_IP }}' 
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './build/*'  
          remote_path: '/home/${{ secrets.SERVER_USERNAME }}/Algorithm-Market-Frontend/build/'
